services:
  loumo_ui:
    container_name: loumo_ui
    build:
      context: ./loumo-ui
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh -c "npm install && npm run build && npm run start"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:5000/api/"
    # ports:
    #   - "3000:3000"
    networks:
      - caddy-net

networks:
  caddy-net:
    name: caddy-net
    external: true
# correct deployment
