services:
  loumo_ui:
    container_name: loumo_ui
    build:
      context: ./loumo-ui
      dockerfile: Dockerfile
    restart: unless-stopped
    # command: sh -c "npm install && npm run build && npm run start"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://api.loumoshop.com/api"
    ports:
      - "3000:3000"
    networks:
      - caddy-network

networks:
  caddy-network:
    driver: bridge
    attachable: true
# correct deployment on sidiki vps
