services:
  loumo:
    container_name: loumo
    build:
      context: ./loumo-ui
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:5000/api/"
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    attachable: true
# correct deployment
