// RootLayout.tsx (async server component)

import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "react18-json-view/src/style.css";
import QueryProvider from "@/providers/queryProvider";
// import NotificationProvider from "@/providers/notifications";
import { getLocale } from "next-intl/server";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
// import Header from "@/components/header";
// import Notification from "@/components/ui/notification";
// import Footer from "@/components/footer";
// import CartController from "@/components/Cart/CartController";
import Maintenance from "./maintenance";

const font_sans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const font_mono_semibold = localFont({
  variable: "--font-mono-semibold",
  src: "../public/fonts/Aileron-SemiBold.otf",
});
const font_mono_bold = localFont({
  variable: "--font-mono-bold",
  src: "../public/fonts/Aileron-Bold.otf",
});

export const metadata: Metadata = {
  title: "Loumo Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <head>
        {/* Google Identity script */}
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>

      <body
        className={`${font_sans.variable} ${font_mono_bold.variable} ${font_mono_semibold.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale}>
          <QueryProvider>
            {/* <NotificationProvider>
              <Notification />
              <Header />
              <CartController />
              {children}
              <Footer />
            </NotificationProvider> */}
            <Maintenance />
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
