name: Deploy Loumo API

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
        working-directory: ./loumo-ui
      - name: Run linter
        run: npm run lint
        working-directory: ./loumo-ui

  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install deps
  #       run: npm ci
  #       working-directory: ./loumo-ui
  #     - name: Run tests
  #       run: npm test
  #       working-directory: ./loumo-ui
  
  build:
    name: Build API
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
        working-directory: ./loumo-ui
      - name: Build project
        run: npm run build
        working-directory: ./loumo-ui
  
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create release folder on VPS
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M")
          echo "RELEASE_DIR=~/deployments/loumo-shop/releases/$TIMESTAMP" >> $GITHUB_ENV
          echo "DEPLOY_TIME=$TIMESTAMP" >> $GITHUB_ENV

      - name: Deploy to VPS
        run: |
         ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'bash -s' << EOF
            set -euo pipefail

            TIMESTAMP=${{ env.DEPLOY_TIME }}
            RELEASE_DIR=~/deployments/loumo-shop/releases/$TIMESTAMP

            mkdir -p $RELEASE_DIR
            cd $RELEASE_DIR

            git clone https://github.com/${{ github.repository }} temp-clone --depth 1
            mv temp-clone/* temp-clone/.* . 2>/dev/null || true
            rm -rf temp-clone

            cp ~/deployments/loumo-shop/shared/.env .env
            export DOCKER_BUILDKIT=0

            # Remove any containers that might conflict
            docker rm -f loumo_ui 2>/dev/null || true

            docker compose -f docker-compose.yml --env-file .env build
            docker compose -f docker-compose.yml --env-file .env up -d

            # Health check loop
            for i in {1..10}; do
              if curl --fail http://localhost:3000/api/health; then
                echo "✅ Health check passed"
                break
              fi
              echo "⏳ Waiting for app to be ready... ($i/10)"
              sleep 6
            done

            if curl --fail http://localhost:3000/api/health; then
              ln -sfn $RELEASE_DIR ~/deployments/loumo-shop/current
              echo "✅ Deployment successful"
            else
              echo "❌ Health check failed, rolling back"
              if [ -L ~/deployments/loumo-shop/current ]; then
                PREV=$(readlink ~/deployments/loumo-shop/current)
                docker compose -f $RELEASE_DIR/docker-compose.yml --env-file .env down || true
                ln -sfn $PREV ~/deployments/loumo-shop/current
                docker compose -f $PREV/docker-compose.yml --env-file $PREV/.env up -d
              else
                echo "⚠️ No previous release to roll back to"
              fi
              exit 1
            fi

            echo "🎯 Deployment complete for release $TIMESTAMP"
            exit 0
          EOF

      - name: Confirm remote session is done
        run: echo "🧠 SSH session completed cleanly"
